# Generated by Django 2.0.4 on 2018-04-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(verbose_name='Contest ID')),
                ('name', models.CharField(max_length=250, verbose_name='Contest Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
            ],
        ),
        migrations.CreateModel(
            name='ContestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=5, verbose_name='Index')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Contest', verbose_name='Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Division Name')),
                ('number', models.IntegerField(verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Division', verbose_name='Division')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Problem Name')),
                ('contest_info', models.ManyToManyField(to='filter.ContestInfo', verbose_name='Contest Info')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='filter.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='contest',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Kind', verbose_name='Kind'),
        ),
    ]
